language: java

jdk:
  - oraclejdk8

script:
  - mvn clean package -Dmaven.test.skip=true
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 702388a4-8f2a-416c-a60b-f0802c8c83c6
